### ISSUE TITLE
为啥语料换成我自己的就不行了。。

### ISSUE THREAD

**Issue by LuckyPickleZZ** [shiyybua/NER#20]
您好我用您给的source和target是可以训练的，但是有个问题是换成我自己的就不行了。我之前用crf进行sequence labling，写了个脚本把之前的语料处理了一下变成您的格式，语料和标注的格式跟您的完全一样，训练的时候也没有报错，就是没有反应。我开始以为是太多了，后来我取了几十k的测试，还是没反应，请问您碰到过吗

**Comment by Yolanda-Ling-Li** [comment]
我也是这个问题，想问一下您最后是怎么解决的呀
