### ISSUE TITLE
兄弟一直报这个错，能帮忙看一下吗

### ISSUE THREAD

**Issue by slblcx** [shiyybua/NER#29]
OutOfRangeError (see above for traceback): Read fewer bytes than requested
	 [[Node: index_to_string/table_init = InitializeTableFromTextFileV2[delimiter="\t", key_index=-1, value_index=-2, vocab_size=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](index_to_string, string_to_index/hash_table/table_init/asset_filepath)]]

**Comment by chunguGuo** [comment]
兄弟，这个问题如何解决的啊？可以指点迷津不。。

**Comment by slblcx** [comment]
你是不是运行的utils代码
